apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config-map
  namespace: default
data:
  const SERVER_CONFIG: "{}"
  SERVER_CONFIG.nodePort: "31244"//9001
  SERVER_CONFIG.redisHostUrl: "localhost"
  SERVER_CONFIG.redisPortUrl: "6379"
  SERVER_CONFIG.apiBaseUrl: "http://192.168.1.7:31241/" //Please update worker1 IP Address here
  SERVER_CONFIG.kongBaseUrl: "http://localhost:8001"
  SERVER_CONFIG.loginBundlePath: "http://localhost:9000/login.js"
  SERVER_CONFIG.bundlePath: "http://localhost:9000/bundle.js"
  SERVER_CONFIG.webDevServer: "http://localhost:9000/"
  
  if (process.env.NODE_ENV == 'production') {
      SERVER_CONFIG.loginBundlePath: "/dist/login.js"
      SERVER_CONFIG.bundlePath: "/dist/bundle.js"
      SERVER_CONFIG.apiBaseUrl: "http://192.168.1.7:31241/" 
      SERVER_CONFIG.redisHostUrl: "172.19.0.2:6379"
  }
  global.serverConfig: SERVER_CONFIG
  exports.serverConfig: SERVER_CONFIG
